first_name = input("Введите ваше имя:")
last_name = input("Введите вашу фамилию:")
age = input("Введите ваш возраст:")
city = input("Введите город проживания:")
print ("Name:", first_name)
print()
print ("Family:", last_name)
print ("Vozrast:", age)
print ("Sity:", city)